-v ${PROJ_DIR}/spi/rtl/spim/spi.vh
-v ${PROJ_DIR}/spi/rtl/spim/spim_intf.sv
-v ${PROJ_DIR}/spi/rtl/spim/spim_reg_top.sv
-v ${PROJ_DIR}/spi/rtl/spim/spim_reg.sv
-v ${PROJ_DIR}/spi/rtl/spim/spimavb.sv
-v ${PROJ_DIR}/spi/rtl/spim/spim_top.sv
-v ${PROJ_DIR}/spi/rtl/spim/clk_gate_beh.sv
-v ${PROJ_DIR}/spi/rtl/spim/pulse_sync.sv
-v ${PROJ_DIR}/common/rtl/asyncfifo.sv
-v ${PROJ_DIR}/common/rtl/syncfifo_mem1r1w.sv
-v ${PROJ_DIR}/common/rtl/levelsync.sv
-v ${PROJ_DIR}/common/rtl/levelsync_sr.sv
-v ${PROJ_DIR}/common/rtl/rst_regen_low.sv

