    //=================================================================================
    // Pair one AIB IOs
    //=================================================================================
    wire [PAD_NUM_HI-1:0] m1_iopad_ch0_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch0_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch1_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch1_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch2_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch2_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch3_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch3_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch4_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch4_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch5_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch5_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch6_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch6_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch7_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch7_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch8_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch8_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch9_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch9_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch10_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch10_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch11_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch11_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch12_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch12_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch13_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch13_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch14_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch14_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch15_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch15_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch16_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch16_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch17_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch17_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch18_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch18_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch19_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch19_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch20_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch20_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch21_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch21_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch22_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch22_aib;
    wire [PAD_NUM_HI-1:0] m1_iopad_ch23_aib;
    wire [PAD_NUM_LO-1:0] s1_iopad_ch23_aib;
    //=================================================================================
    // Pair Two AIB bump
    //=================================================================================
    wire [PAD_NUM_HI-1:0] m2_iopad_ch0_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch0_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch1_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch1_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch2_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch2_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch3_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch3_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch4_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch4_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch5_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch5_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch6_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch6_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch7_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch7_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch8_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch8_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch9_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch9_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch10_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch10_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch11_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch11_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch12_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch12_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch13_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch13_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch14_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch14_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch15_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch15_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch16_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch16_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch17_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch17_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch18_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch18_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch19_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch19_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch20_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch20_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch21_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch21_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch22_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch22_aib;
    wire [PAD_NUM_HI-1:0] m2_iopad_ch23_aib;
    wire [PAD_NUM_HI-1:0] s2_iopad_ch23_aib;
    //=================================================================================
    logic  [1:0]  ms1_tx_fifo_mode;
    logic  [1:0]  sl1_tx_fifo_mode;
    logic  [1:0]  ms1_rx_fifo_mode;
    logic  [1:0]  sl1_rx_fifo_mode;
    logic  [1:0]  ms2_tx_fifo_mode;
    logic  [1:0]  sl2_tx_fifo_mode;
    logic  [1:0]  ms2_rx_fifo_mode;
    logic  [1:0]  sl2_rx_fifo_mode;

    logic  [4:0]  ms1_tx_markbit;
    logic  [4:0]  sl1_tx_markbit;
    logic  [4:0]  ms2_tx_markbit;
    logic  [4:0]  sl2_tx_markbit;
    logic         ms1_gen1;
    logic         sl1_gen1;
    logic         ms2_gen1;
    logic         sl2_gen1;
    logic         ms1_lpbk;
    logic         sl1_lpbk;
    logic         ms2_lpbk;
    logic         sl2_lpbk;

    logic         ms1_dbi_en;
    logic         sl1_dbi_en;
    logic         ms2_dbi_en;
    logic         sl2_dbi_en;
    logic [31:0]  rdata_reg;

    logic         avmm_rstn;
    logic  avmm_clk = 1'b0;
    logic  spi_clk = 1'b0;
    logic  osc_clk = 1'b0;
    logic  p1_wr_clk = 1'b0;
    logic  p1_rd_clk = 1'b0;
    logic  p1_fwd_clk = 1'b0;
    logic  p2_wr_clk = 1'b0;
    logic  p2_rd_clk = 1'b0;
    logic  p2_fwd_clk = 1'b0;
    int run_for_n_pkts_ms1;
    int run_for_n_pkts_sl1;
    int run_for_n_pkts_ms2;
    int run_for_n_pkts_sl2;

    int run_for_n_wa_cycle;
    int err_count;
    
    logic [40*24-1:0] ms1_rcv_40b_q [$];
    
    logic [80*24-1:0] sl1_rcv_80b_q [$];
    logic [80*24-1:0] ms1_rcv_80b_q [$];
    
    logic [320*24-1:0] sl1_rcv_320b_q [$];
    logic [320*24-1:0] ms1_rcv_320b_q [$];

    logic [320*24-1:0] sl2_rcv_320b_q [$];
    logic [320*24-1:0] ms2_rcv_320b_q [$];
    bit [1023:0] status;

