${TESTBENCH_DIR}/top/abstract_class_pkg.sv
${TESTBENCH_DIR}/top/clk_gen.sv
${TESTBENCH_DIR}/top/delay_unit.v
${TESTBENCH_DIR}/top/delay_clk_unit.v
${TESTBENCH_DIR}/params/aib/aib_param_pkg.sv
${TESTBENCH_DIR}/aib2.0/tb_emib.sv
${TESTBENCH_DIR}/macro/common_defines.svh
${TESTBENCH_DIR}/macro/macro_clk_gen.svh
${TESTBENCH_DIR}/macro/macro_intf_inst.svh
${TESTBENCH_DIR}/macro/macro_tb_dut_inst.svh
${TESTBENCH_DIR}/macro/macro_intf_to_uvm.svh
${TESTBENCH_DIR}/aib_uvm/aib_test/aib_test_macros.svh
${TESTBENCH_DIR}/interface/aib_mac_if.sv
${TESTBENCH_DIR}/interface/avalon_mm_if.sv
${TESTBENCH_DIR}/interface/dut_bump_if.sv
${TESTBENCH_DIR}/interface/vclock_if.sv
${TESTBENCH_DIR}/interface/dut_if_mac.sv
${TESTBENCH_DIR}/interface/ca_if.sv
${TESTBENCH_DIR}/top/tb_dut_wrapper_m0.sv
${TESTBENCH_DIR}/top/tb_dut_wrapper_s0.sv
${TESTBENCH_DIR}/aib2.0/tb_aib2_dut_wrapper_m0.sv
${TESTBENCH_DIR}/aib2.0/tb_aib2_dut_wrapper_s0.sv

${CA_DV_HOME}/tb/ca_GENERATED_defines.svh
${PROJ_DIR}/common/dv/p2p_lite.sv
+incdir+${CA_DV_HOME}/tb/
+incdir+${PROJ_DIR}/common/dv/reset_agent/
+incdir+${CA_DV_HOME}/export_src/chan_delay_agent/
${PROJ_DIR}/common/dv/reset_agent/reset_pkg.svh
${PROJ_DIR}/common/dv/reset_agent/reset_if.sv
${CA_DV_HOME}/export_src/chan_delay_agent/chan_delay_pkg.svh
${CA_DV_HOME}/export_src/chan_delay_agent/chan_delay_if.sv
+incdir+${CA_DV_HOME}/export_src/
${CA_DV_HOME}/local_src/ca_gen_if.sv
${CA_DV_HOME}/export_src/ca_data_pkg.svh
${CA_DV_HOME}/export_src/ca_tx_tb_out_if.sv
${CA_DV_HOME}/export_src/ca_tx_tb_out_pkg.svh
${CA_DV_HOME}/export_src/ca_tx_tb_in_if.sv
${CA_DV_HOME}/export_src/ca_tx_tb_in_pkg.svh
${CA_DV_HOME}/export_src/ca_rx_tb_in_if.sv
${CA_DV_HOME}/export_src/ca_rx_tb_in_pkg.svh
${CA_DV_HOME}/ca_pkg.svh
${PROJ_DIR}/common/dv/marker_gen.sv
${PROJ_DIR}/common/dv/strobe_gen.sv
${CA_DV_HOME}/tb/ca_DUT_wrapper.sv
${CA_DV_HOME}/tb/ca_top_tb.sv
