#!/bin/bash

export AIB_PHY="$(pwd)/../../../../aib-phy-hardware-master"
export AIB2_RTL_ROOT="$AIB_PHY/v2.0/rev1/rtl"
export MAIB_RTL_ROOT="$AIB_PHY/v1.0/rev2/rtl/v1_slave"
export SPI_ROOT="$(pwd)/../../rtl"
export AIB_DV="$AIB_PHY/v2.0/rev1/dv"

vlogan -sverilog  +v2k -full64 +vcs+vcdpluson -timescale=1ps/1ps +define+VCS  -f ../flist/aib2.cf -l compile_aib2.log

vlogan -sverilog  +v2k -full64 -timescale=1ps/1ps +define+TIMESCALE_EN+VCS+BEHAVIORAL+MAIB_PIN96+ALTR_HPS_INTEL_MACROS_OFF  -f ../flist/maib.cf -l compile_maib.log

vlogan -sverilog  +v2k -full64 +vcs+vcdpluson -timescale=1ps/1ps -f ../flist/spi_rtl.cf -l compile_spi.log

vlogan -sverilog  +v2k -full64  -timescale=1ps/1ps -f ../flist/tb_rtl.cf -l compile_tb.log

vcs -debug_acc+all -full64 +lint=TFIPC-L +error+100 +lint=PCWM  -top top_tb -l vcs.log -lca -cm line+cond+tgl+fsm+path+branch+assert

./simv -cm line+cond+tgl+fsm+path+branch+assert

