#!/bin/csh -f

## ////////////////////////////////////////////////////////////////////////////////////////////////////
## //
## //        Copyright (C) 2021 Eximius Design
## //                All Rights Reserved
## //
## //
## // Licensed under the Apache License, Version 2.0 (the "License");
## // you may not use this file except in compliance with the License.
## // You may obtain a copy of the License at
## //
## //     http://www.apache.org/licenses/LICENSE-2.0
## //
## // Unless required by applicable law or agreed to in writing, software
## // distributed under the License is distributed on an "AS IS" BASIS,
## // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## // See the License for the specific language governing permissions and
## // limitations under the License.
## //
## // Functional Descript: Channel Alignment Test run File
## //
## // run is as:   ./run_sim
## //
## ////////////////////////////////////////////////////////////////////////////////////////////////////


set d_cfg   = "sailrock_cfg.txt"
set mfile   = "makefile"
set sdir    = "scripts"

set ver     = `grep "aib_ver" $d_cfg`
set run_ver = m$ver[2]s$ver[3]
echo "$d_cfg is $run_ver mode"

set rep     = `grep "MODE :=" makefile`
set new_rep = `echo "MODE := $run_ver"`

echo "Replace $mfile from ==${rep}== to MODE := $run_ver"
## sed -i 's#'$rep'#MODE := '$run_ver'#g' $mfile
sed -i "s/$rep/$new_rep/g" $mfile

set scenario = "ca_basic_test_c"

make SCENARIO=$scenario run_all
