${PROJ_DIR}/ca/rtl/ca.sv
${PROJ_DIR}/ca/rtl/ca_tx_strb.sv
${PROJ_DIR}/ca/rtl/ca_rx_align.sv
${PROJ_DIR}/ca/rtl/ca_rx_align_fifo.sv
${PROJ_DIR}/ca/rtl/ca_tx_mux.sv
${PROJ_DIR}/common/rtl/asyncfifo.sv
${PROJ_DIR}/common/rtl/syncfifo_mem1r1w.sv
${PROJ_DIR}/common/rtl/levelsync.sv
${PROJ_DIR}/common/rtl/rst_regen_low.sv
${PROJ_DIR}/common/rtl/syncfifo.sv
${PROJ_DIR}/common/rtl/syncfifo_reg.sv
${PROJ_DIR}/common/rtl/syncfifo_ram.sv
